(function() {var implementors = {};
implementors["allychain_template_runtime"] = [{"text":"impl&lt;Block:&nbsp;BlockT, C:&nbsp;CallApiAt&lt;Block&gt;&gt; ApiExt&lt;Block&gt; for <a class=\"struct\" href=\"allychain_template_runtime/struct.RuntimeApiImpl.html\" title=\"struct allychain_template_runtime::RuntimeApiImpl\">RuntimeApiImpl</a>&lt;Block, C&gt;","synthetic":false,"types":["allychain_template_runtime::RuntimeApiImpl"]}];
implementors["betanet_runtime"] = [{"text":"impl&lt;Block:&nbsp;BlockT, C:&nbsp;CallApiAt&lt;Block&gt;&gt; ApiExt&lt;Block&gt; for <a class=\"struct\" href=\"betanet_runtime/struct.RuntimeApiImpl.html\" title=\"struct betanet_runtime::RuntimeApiImpl\">RuntimeApiImpl</a>&lt;Block, C&gt;","synthetic":false,"types":["betanet_runtime::RuntimeApiImpl"]}];
implementors["cumulus_test_runtime"] = [{"text":"impl&lt;Block:&nbsp;BlockT, C:&nbsp;CallApiAt&lt;Block&gt;&gt; ApiExt&lt;Block&gt; for <a class=\"struct\" href=\"cumulus_test_runtime/struct.RuntimeApiImpl.html\" title=\"struct cumulus_test_runtime::RuntimeApiImpl\">RuntimeApiImpl</a>&lt;Block, C&gt;","synthetic":false,"types":["cumulus_test_runtime::RuntimeApiImpl"]}];
implementors["cumulus_test_runtime_upgrade"] = [{"text":"impl&lt;Block:&nbsp;BlockT, C:&nbsp;CallApiAt&lt;Block&gt;&gt; ApiExt&lt;Block&gt; for <a class=\"struct\" href=\"cumulus_test_runtime_upgrade/struct.RuntimeApiImpl.html\" title=\"struct cumulus_test_runtime_upgrade::RuntimeApiImpl\">RuntimeApiImpl</a>&lt;Block, C&gt;","synthetic":false,"types":["cumulus_test_runtime_upgrade::RuntimeApiImpl"]}];
implementors["shell_runtime"] = [{"text":"impl&lt;Block:&nbsp;BlockT, C:&nbsp;CallApiAt&lt;Block&gt;&gt; ApiExt&lt;Block&gt; for <a class=\"struct\" href=\"shell_runtime/struct.RuntimeApiImpl.html\" title=\"struct shell_runtime::RuntimeApiImpl\">RuntimeApiImpl</a>&lt;Block, C&gt;","synthetic":false,"types":["shell_runtime::RuntimeApiImpl"]}];
implementors["statemine_runtime"] = [{"text":"impl&lt;Block:&nbsp;BlockT, C:&nbsp;CallApiAt&lt;Block&gt;&gt; ApiExt&lt;Block&gt; for <a class=\"struct\" href=\"statemine_runtime/struct.RuntimeApiImpl.html\" title=\"struct statemine_runtime::RuntimeApiImpl\">RuntimeApiImpl</a>&lt;Block, C&gt;","synthetic":false,"types":["statemine_runtime::RuntimeApiImpl"]}];
implementors["statemint_runtime"] = [{"text":"impl&lt;Block:&nbsp;BlockT, C:&nbsp;CallApiAt&lt;Block&gt;&gt; ApiExt&lt;Block&gt; for <a class=\"struct\" href=\"statemint_runtime/struct.RuntimeApiImpl.html\" title=\"struct statemint_runtime::RuntimeApiImpl\">RuntimeApiImpl</a>&lt;Block, C&gt;","synthetic":false,"types":["statemint_runtime::RuntimeApiImpl"]}];
implementors["westmint_runtime"] = [{"text":"impl&lt;Block:&nbsp;BlockT, C:&nbsp;CallApiAt&lt;Block&gt;&gt; ApiExt&lt;Block&gt; for <a class=\"struct\" href=\"westmint_runtime/struct.RuntimeApiImpl.html\" title=\"struct westmint_runtime::RuntimeApiImpl\">RuntimeApiImpl</a>&lt;Block, C&gt;","synthetic":false,"types":["westmint_runtime::RuntimeApiImpl"]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()